site_name: Woulf
site_url: https://woulf.dev
site_author: woulf
site_description: >-
  Personal links and homepage.

# repo_url: https://github.com/woulfdev/woulf-dev

extra_css:
  - stylesheets/extra.css

plugins: 
  # - optimize
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_date
  - privacy
  - blog:
      blog_dir: projects
      blog_toc: true
      post_url_date_format: yyyy
      archive: false

markdown_extensions: 
  - tables
  - md_in_html
  - attr_list
  - pymdownx.blocks.caption

theme:
  langauge: en
  name: material
  custom_dir: overrides
  font: 
    text: Quicksand
  logo: assets/img/avatars/woulf/woulf-no-bg.svg
  favicon: assets/img/favicon.png
  features:
    # - content.action.view
    # - header.autohide
    - navigation.instant
    # - navigation.instant.progress
    - navigation.tabs
    # - navigation.footer
    - navigation.indexes
    # - navigation.sections
    # - search.suggest
    # - search.highlight
    # - content.tooltips
  icon: 
    repo: fontawesome/brands/github
    annotation: material/circle-medium
  palette: 
      scheme: slate

not_in_nav: 
  lost-and-found.md

nav:
  - Home: index.md
  - Projects:
    - projects/index.md
